### ISSUE TITLE
Issue in readme example

### ISSUE THREAD

**Issue by UltCombo** [eugeneware/unique-stream#6]
One of the readme examples contains `--count && end();` which IMO does not make much sense. That is, `--count` evaluates to `2` which is truthy and calls `end()` in the first iteration. I believe it should be `--count || end();`, or make it more clear with `if (!--count) end();` or `if (--count === 0) end();`

**Comment by eugeneware** [comment]
Thanks. Have fixed this in the README. Should have been `--count || end()`
